//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqLabRab.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinqLabRab.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IdDirect;NameDirect;MinBall;Limit
        ///1;ПИнб;210;15
        ///2;ПИб;185;10
        ///3;ИСб;200;12.
        /// </summary>
        internal static string directions {
            get {
                return ResourceManager.GetString("directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IdStudent;NameStudent;Sex;BallMath;BallLang;BallInf;IdDirect
        ///1;Иванов;м;60;70;80;1
        ///2;Петров;м;60;62;60;2
        ///3;Яценко;ж;70;77;70;3
        ///4;Бойко;ж;60;64;62;2
        ///5;Миков;м;60;70;88;1
        ///6;Мищенко;ж;60;52;60;3
        ///7;Ямбург;ж;70;77;75;3
        ///8;Абросов;м;56;62;62;2
        ///9;Кикова;ж;66;75;80;1
        ///10;Кикабидзе;ж;54;62;60;1
        ///11;Луканин;м;70;75;90;3
        ///12;Жданов;м;68;66;62;2
        ///13;Маков;м;60;70;50;1
        ///14;Сынбаева;ж;60;52;50;2
        ///15;Занозкина;ж;70;57;70;3
        ///16;Машина;ж;60;54;62;2
        ///17;Градский;м;62;57;70;1
        ///18;Петровский;м;60;62;66;2
        ///19;Берг;ж;74; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string students {
            get {
                return ResourceManager.GetString("students", resourceCulture);
            }
        }
    }
}
